In [43]:
import numpy as np

arr = np.arange(0, 24)
len(arr)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
arr.shape

(24,)

In [45]:
v = arr.reshape([6,4])
v.shape

(6, 4)

In [46]:
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
v.ndim

3

In [26]:
v.sum() # case 1: axis=None

496

In [28]:
res01 = v.sum(axis=0) # axis=0
res01.shape

(2, 4)

In [29]:
res01

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [31]:
res02=v.sum(axis=1)
res02.shape

(4, 4)